services:
  # NATS JetStream service (required for service registry)
  nats:
    image: nats:2.10-alpine
    container_name: aegistrader-nats
    ports:
      - "${NATS_CLIENT_PORT:-4222}:4222"  # NATS client port
      - "${NATS_MONITOR_PORT:-8222}:8222"  # NATS monitoring port
    command: ["-js", "-m", "8222"]
    networks:
      - aegis-network

  # Management Service (FastAPI)
  monitor-api:
    build:
      context: .
      dockerfile: apps/monitor-api/Dockerfile
      args:
        - HTTP_PROXY=${HTTP_PROXY:-}
        - HTTPS_PROXY=${HTTPS_PROXY:-}
        - NO_PROXY=${NO_PROXY:-localhost,127.0.0.1}
    container_name: aegistrader-monitor-api
    ports:
      - "${API_PORT:-8100}:8100"
    environment:
      - NATS_URL=${NATS_URL:-nats://nats:4222}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - API_PORT=${API_PORT:-8100}
    depends_on:
      - nats
    networks:
      - aegis-network

  # Monitor UI (Next.js)
  monitor-ui:
    build:
      context: .
      dockerfile: apps/monitor-ui/Dockerfile
      args:
        - HTTP_PROXY=${HTTP_PROXY:-}
        - HTTPS_PROXY=${HTTPS_PROXY:-}
        - NO_PROXY=${NO_PROXY:-localhost,127.0.0.1}
        - NPM_REGISTRY=${NPM_REGISTRY:-https://registry.npmmirror.com}
    container_name: aegistrader-monitor-ui
    ports:
      - "${UI_PORT:-3100}:3100"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://monitor-api:8100}
      - PORT=${UI_PORT:-3100}
    depends_on:
      - monitor-api
    networks:
      - aegis-network

networks:
  aegis-network:
    driver: bridge