{{- if .Values.createNamespace -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    {{- include "aegis-trader.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: aegis-trader
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
{{- end }}