{{- if .Values.postInstall.createKvBucket.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "aegis-trader.fullname" . }}-create-kv-bucket
  labels:
    {{- include "aegis-trader.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "aegis-trader.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: post-install-job
    spec:
      restartPolicy: OnFailure
      containers:
        - name: create-kv-bucket
          image: natsio/nats-box:latest
          command:
            - sh
            - -c
            - |
              echo "Waiting for NATS to be ready..."
              until nats server check connection --server=nats://{{ .Release.Name }}-nats:4222; do
                echo "NATS not ready, waiting..."
                sleep 2
              done
              echo "NATS is ready!"

              # Check if bucket already exists
              if nats kv ls --server=nats://{{ .Release.Name }}-nats:4222 | grep -q "{{ .Values.postInstall.createKvBucket.bucketName }}"; then
                echo "KV bucket '{{ .Values.postInstall.createKvBucket.bucketName }}' already exists"
              else
                echo "Creating KV bucket '{{ .Values.postInstall.createKvBucket.bucketName }}'..."
                nats kv add {{ .Values.postInstall.createKvBucket.bucketName }} \
                  --server=nats://{{ .Release.Name }}-nats:4222 \
                  --replicas=3 \
                  --ttl=60s
                echo "KV bucket created successfully"
              fi
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
{{- end }}
