# Kubernetes deployment
# This template is designed to work with Helm
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "market-service.fullname" . }}
  labels:
    {{- include "market-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "market-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "market-service.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
      - name: vnpy-fix-scripts
        configMap:
          name: vnpy-fix-scripts
          defaultMode: 0755
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/scripts/docker-entrypoint.sh"]
        volumeMounts:
        - name: vnpy-fix-scripts
          mountPath: /scripts
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort | default 8080 }}
          protocol: TCP
        env:
        - name: NATS_URL
          value: "nats://aegis-trader-nats:4222"
        - name: SERVICE_NAME
          value: "market-service"
        - name: SERVICE_VERSION
          value: "{{ .Chart.AppVersion }}"
        - name: SERVICE_INSTANCE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ENABLE_CTP_GATEWAY
          value: "{{ .Values.ctp.enabled }}"
        envFrom:
        - secretRef:
            name: ctp-credentials
        {{- if .Values.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: {{ .Values.livenessProbe.path }}
            port: http
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
        {{- end }}
        {{- if .Values.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            path: {{ .Values.readinessProbe.path }}
            port: http
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
