# RBAC configuration for GitHub Actions CI/CD
---
apiVersion: v1
kind: Namespace
metadata:
  name: aegis-staging
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-actions
  namespace: aegis-staging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: github-actions-deployer
  namespace: aegis-staging
rules:
# Core resources
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "configmaps", "secrets", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# Deployments, ReplicaSets, StatefulSets
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "statefulsets", "daemonsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# Jobs and CronJobs
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# Ingress
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses", "networkpolicies"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# Service Accounts and RBAC (for Helm)
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# HorizontalPodAutoscaler
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# PodDisruptionBudget
- apiGroups: ["policy"]
  resources: ["poddisruptionbudgets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# For kubectl exec (smoke tests)
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
# For kubectl logs
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-actions-deployer
  namespace: aegis-staging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: github-actions-deployer
subjects:
- kind: ServiceAccount
  name: github-actions
  namespace: aegis-staging
---
# ClusterRole for namespace creation (needed for CI/CD)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: github-actions-namespace-creator
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: github-actions-namespace-creator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: github-actions-namespace-creator
subjects:
- kind: ServiceAccount
  name: github-actions
  namespace: aegis-staging