# Production environment values for test-example
# Override default values for production

replicaCount: 3

image:
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

logLevel: INFO

# Production NATS cluster
nats:
  url: "nats://nats.production.svc.cluster.local:4222"

# Enable ingress for production
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: test-example.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: test-example-tls  # pragma: allowlist secret
      hosts:
        - test-example.example.com
