apiVersion: v2
name: monitor-api
description: AegisTrader Management Service (FastAPI)
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - fastapi
  - api
  - management
home: https://github.com/AegisTrader
maintainers:
  - name: AegisTrader Team
    email: support@aegistrader.io