# Default values for monitor-api
replicaCount: 1

image:
  repository: aegis-trader/monitor-api
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65534
  runAsGroup: 65534
  fsGroup: 65534
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65534
  capabilities:
    drop:
    - ALL

service:
  type: ClusterIP
  port: 8100

env:
  NATS_URL: "nats://aegis-trader-nats:4222"
  NATS_KV_BUCKET: "service-registry"

resources:
  requests:
    cpu: 1000m
    memory: 2Gi
  limits:
    cpu: 1000m
    memory: 2Gi

probes:
  liveness:
    enabled: true
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 10
    periodSeconds: 10
  readiness:
    enabled: true
    httpGet:
      path: /ready
      port: http
    initialDelaySeconds: 30
    periodSeconds: 5
  startup:
    enabled: true
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 0
    periodSeconds: 10
    failureThreshold: 60

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
