USER-SUPPLIED VALUES:
createNamespace: false
development:
  monitor-api:
    replicaCount: 1
  monitor-ui:
    replicaCount: 1
  nats:
    nats:
      jetstream:
        fileStorage:
          size: 5Gi
global:
  environment: development
  imagePullSecrets: []
  storageClass: ""
monitor-api:
  enabled: true
  env:
    NATS_KV_BUCKET: service-registry
  image:
    pullPolicy: IfNotPresent
    repository: aegistrader-monitor-api
    tag: latest
  probes:
    liveness:
      enabled: true
      httpGet:
        path: /health
        port: http
      initialDelaySeconds: 10
      periodSeconds: 10
    readiness:
      enabled: true
      httpGet:
        path: /ready
        port: http
      initialDelaySeconds: 30
      periodSeconds: 5
    startup:
      enabled: true
      failureThreshold: 60
      httpGet:
        path: /health
        port: http
      initialDelaySeconds: 0
      periodSeconds: 10
  replicaCount: 1
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 1000m
      memory: 2Gi
  service:
    port: 8100
    type: ClusterIP
monitor-ui:
  enabled: true
  env: null
  image:
    pullPolicy: IfNotPresent
    repository: aegistrader-monitor-ui
    tag: latest
  ingress:
    annotations: {}
    className: ""
    enabled: false
    hosts:
    - host: aegis-trader.local
      paths:
      - path: /
        pathType: Prefix
    tls: []
  probes:
    liveness:
      enabled: true
      httpGet:
        path: /
        port: http
      initialDelaySeconds: 10
      periodSeconds: 10
    readiness:
      enabled: true
      httpGet:
        path: /
        port: http
      initialDelaySeconds: 10
      periodSeconds: 5
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 1Gi
  service:
    port: 3100
    type: ClusterIP
nats:
  config:
    jetstream:
      enabled: true
      fileStore:
        dir: /data
        enabled: true
        pvc:
          enabled: true
          size: 10Gi
      merge:
        allow_msg_ttl: true
        limit_markers_ttl: 3600s
  container:
    env:
      GOMEMLIMIT: 7GiB
    merge:
      resources:
        limits:
          cpu: "2"
          memory: 8Gi
        requests:
          cpu: "1"
          memory: 4Gi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        runAsNonRoot: true
        runAsUser: 1000
  enabled: true
  nats:
    jetstream:
      enabled: true
      fileStorage:
        enabled: true
        size: 10Gi
        storageClassName: ""
      memoryStorage:
        enabled: false
        size: 1Gi
  podTemplate:
    merge:
      spec:
        securityContext:
          fsGroup: 1000
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
    topologySpreadConstraints:
      kubernetes.io/hostname:
        maxSkew: 1
        whenUnsatisfiable: DoNotSchedule
  promExporter:
    enabled: false
  replicas: 3
  service:
    type: ClusterIP
serviceRegistry:
  bucket:
    maxBytes: 1073741824
    maxMsgSize: 1048576
    maxMsgs: -1
    replicas: 3
    ttl: 0
  bucketName: service-registry
  createBucket: true
