# Default values for aegis-trader
# This is a YAML-formatted file
# Declare variables to be passed into your templates

# Create namespace
createNamespace: false

global:
  # Global image pull secrets
  imagePullSecrets: []
  # Global storage class
  storageClass: ""
  # Environment: development, staging, production
  environment: development

# NATS Configuration
nats:
  enabled: true
  # Number of NATS replicas
  replicas: 3
  # NATS container configuration
  nats:
    jetstream:
      enabled: true
      # JetStream file storage configuration
      fileStorage:
        enabled: true
        size: 10Gi
        storageClassName: "" # Uses default if empty
      # Memory storage configuration (for development)
      memoryStorage:
        enabled: false
        size: 1Gi
  # Container configuration
  container:
    env:
      # Go memory limit for efficiency (leave ~1GiB for OS)
      GOMEMLIMIT: 7GiB
    # Resource limits and security context for NATS container
    merge:
      resources:
        requests:
          cpu: "1"
          memory: 4Gi
        limits:
          cpu: "2"
          memory: 8Gi
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 1000
        capabilities:
          drop:
          - ALL
  # Service configuration
  service:
    type: ClusterIP
  # Pod configuration
  podTemplate:
    # Security context for pod
    merge:
      spec:
        securityContext:
          fsGroup: 1000
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
    # Topology spread for HA
    topologySpreadConstraints:
      kubernetes.io/hostname:
        maxSkew: 1
        whenUnsatisfiable: DoNotSchedule
  # Monitoring configuration
  promExporter:
    enabled: false # Enable for production monitoring

# Management Service (FastAPI) Configuration
monitor-api:
  enabled: true
  replicaCount: 1
  image:
    repository: aegistrader-monitor-api
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: ClusterIP
    port: 8100
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      cpu: 1000m
      memory: 2Gi
  probes:
    liveness:
      enabled: true
      httpGet:
        path: /health
        port: http
      initialDelaySeconds: 10
      periodSeconds: 10
    readiness:
      enabled: true
      httpGet:
        path: /ready
        port: http
      initialDelaySeconds: 30
      periodSeconds: 5
    startup:
      enabled: true
      httpGet:
        path: /health
        port: http
      initialDelaySeconds: 0
      periodSeconds: 10
      failureThreshold: 60
  env:
    # NATS_URL 将在部署模板中动态生成
    NATS_KV_BUCKET: "service-registry"

# Monitor UI (Next.js) Configuration  
monitor-ui:
  enabled: true
  replicaCount: 1
  image:
    repository: aegistrader-monitor-ui
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: ClusterIP
    port: 3100
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 500m
      memory: 1Gi
  probes:
    liveness:
      enabled: true
      httpGet:
        path: /
        port: http
      initialDelaySeconds: 10
      periodSeconds: 10
    readiness:
      enabled: true
      httpGet:
        path: /
        port: http
      initialDelaySeconds: 10
      periodSeconds: 5
  env:
    # NEXT_PUBLIC_API_URL will be set by values.deployment.yaml
  ingress:
    enabled: false
    className: ""
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: aegis-trader.local
        paths:
          - path: /
            pathType: Prefix
    tls: []
    #  - secretName: aegis-trader-tls
    #    hosts:
    #      - aegis-trader.local
  # Probes already defined in subchart values.yaml

# Service Registry Configuration
serviceRegistry:
  # Create KV bucket for service registry
  createBucket: true
  bucketName: service-registry
  # Bucket configuration
  bucket:
    replicas: 3
    ttl: 0 # No TTL by default
    maxBytes: 1073741824 # 1GB
    maxMsgs: -1 # Unlimited
    maxMsgSize: 1048576 # 1MB

# Development overrides
development:
  # Use local storage for development
  nats:
    nats:
      jetstream:
        fileStorage:
          size: 5Gi
  # Single replica for development
  monitor-api:
    replicaCount: 1
  monitor-ui:
    replicaCount: 1