# Development environment overrides
# Use with: helm install aegis-trader ./helm -f ./helm/values.dev.yaml

# NATS Configuration for development
nats:
  # Single replica for development
  replicas: 1
  nats:
    jetstream:
      fileStorage:
        size: 5Gi
        storageClassName: "standard" # Default for minikube/kind
    resources:
      requests:
        cpu: "0.5"
        memory: 2Gi
      limits:
        cpu: "1"
        memory: 2Gi
  container:
    env:
      GOMEMLIMIT: 1800MiB
  # Disable topology constraints for single node
  podTemplate:
    topologySpreadConstraints: []

# Reduce resources for development
monitor-api:
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi

monitor-ui:
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
  # Enable ingress for local development
  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: aegis-trader.local
        paths:
          - path: /
            pathType: Prefix

# Service Registry for development
serviceRegistry:
  bucket:
    replicas: 1
    maxBytes: 104857600 # 100MB for dev
