# JetStream-enabled configuration for NATS
# This ensures JetStream is properly configured for TTL support

nats:
  # Merge additional configuration into NATS config
  config:
    # Ensure JetStream is enabled with proper settings
    merge:
      jetstream:
        max_memory_store: 1073741824  # 1GB in bytes
        max_file_store: 10737418240   # 10GB in bytes
        store_dir: /data
        # Enable domain for multi-tenancy (optional but good practice)
        # This should match NATS_JS_DOMAIN in .deploy.env
        domain: aegis  # ${NATS_JS_DOMAIN}

    # Cluster settings for HA
    cluster:
      enabled: true
      replicas: 3

  # Container resources for JetStream workload
  container:
    merge:
      resources:
        requests:
          cpu: "1"
          memory: 4Gi
        limits:
          cpu: "2"
          memory: 8Gi

# Service Registry configuration remains the same
serviceRegistry:
  createBucket: true
  bucketName: service-registry
  bucket:
    replicas: 3
    ttl: 0  # No default TTL - use per-message TTL
    maxBytes: 1073741824  # 1GB
    maxMsgs: -1  # Unlimited
    maxMsgSize: 1048576  # 1MB
