# Test values combining dev overrides
global:
  environment: development

# NATS with clustering disabled for single node
nats:
  enabled: true
  config:
    cluster:
      enabled: false
      replicas: 1
    jetstream:
      enabled: true
      fileStore:
        enabled: true
        dir: /data
        pvc:
          enabled: true
          size: 1Gi
      memoryStore:
        enabled: false
        maxSize: 0
  # KV Store configuration
  kvStore:
    # TTL for service registry entries (in seconds)
    # This controls how long services remain in registry after last heartbeat
    ttlSeconds: 30
  container:
    merge:
      resources:
        requests:
          cpu: "200m"
          memory: 512Mi
        limits:
          cpu: "500m"
          memory: 1Gi

# Monitor API with correct image tag
monitor-api:
  enabled: true
  replicaCount: 1
  image:
    repository: aegistrader-monitor-api
    pullPolicy: IfNotPresent
    tag: "20250807-191635"
  service:
    port: 8100
  containerPort: 8100
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  configMap:
    data:
      API_PORT: "8100"
      NATS_URL: "nats://aegis-trader-nats:4222"
      NATS_KV_BUCKET: "service_registry"
  initContainers:
    - name: wait-for-nats
      image: busybox:1.36
      command: ['sh', '-c']
      args: ['until nc -z aegis-trader-nats 4222; do echo "Waiting for NATS..."; sleep 2; done']
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          cpu: 50m
          memory: 64Mi

# Monitor UI with correct image tag
monitor-ui:
  enabled: true
  replicaCount: 1
  image:
    repository: aegistrader-monitor-ui
    pullPolicy: IfNotPresent
    tag: "20250807-191635"
  service:
    type: ClusterIP
    port: 3100
  waitForApiPort: 8100  # Must match monitor-api port
  env:
    NEXT_PUBLIC_API_URL: "http://aegis-trader-monitor-api:8100"
    PORT: "3100"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 512Mi

# Echo Service - SDK showcase
echo-service:
  enabled: true
  replicaCount: 3
  image:
    repository: aegis-echo-service
    pullPolicy: IfNotPresent
    tag: "20250807-191635"
  service:
    port: 8080
  containerPort: 8080
  # Disable health checks since this is an RPC service
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  configMap:
    data:
      SERVICE_NAME: "echo-service"
      NATS_URL: "nats://aegis-trader-nats:4222"
      SERVICE_VERSION: "1.0.0"
      LOG_LEVEL: "INFO"
  env:
    - name: INSTANCE_ID
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: HOSTNAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
  initContainers:
    - name: wait-for-nats
      image: busybox:1.36
      command: ['sh', '-c']
      args: ['until nc -z aegis-trader-nats 4222; do echo "Waiting for NATS..."; sleep 2; done']
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          cpu: 50m
          memory: 64Mi

# Trading services configuration - DISABLED FOR NOW
order-service:
  enabled: false

pricing-service:
  enabled: false

risk-service:
  enabled: false

# Post-install configuration
postInstall:
  createKvBucket:
    enabled: true
    bucketName: service_registry
  configureTTL:
    enabled: true
