# Development environment overrides
global:
  environment: development

# Monitor API with current deployment image
monitor-api:
  image:
    tag: "20250804-114418"  # Use existing image version
  service:
    port: 8100
  containerPort: 8100
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  configMap:
    data:
      API_PORT: "8100"
      NATS_URL: "nats://aegis-trader-nats:4222"
      NATS_KV_BUCKET: "service-registry"

# Monitor UI with current deployment image
monitor-ui:
  image:
    tag: "20250804-114418"  # Use existing image version
  service:
    port: 3100
  waitForApiPort: 8100  # Must match monitor-api port
  env:
    - name: NEXT_PUBLIC_API_URL
      value: "http://aegis-trader-monitor-api:8100"
    - name: PORT
      value: "3100"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 512Mi

# Reduce resource requirements for local development
nats:
  config:
    cluster:
      enabled: false  # Disable clustering for single node
      replicas: 1  # Single node for dev
  container:
    merge:
      resources:
        requests:
          cpu: "200m"
          memory: 512Mi
        limits:
          cpu: "500m"
          memory: 1Gi

# Trading services configuration for dev
order-service:
  enabled: true
  replicaCount: 2  # Reduced from 3 for dev
  image:
    tag: "20250803-151359"  # Will be updated when image is built
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

pricing-service:
  enabled: true
  replicaCount: 1  # Reduced from 2 for dev
  image:
    tag: "20250803-151359"  # Will be updated when image is built
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

risk-service:
  enabled: true
  replicaCount: 1  # Reduced from 2 for dev
  image:
    tag: "20250803-151359"  # Will be updated when image is built
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi
